id: I575DE051
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:05:23.086648+00:00
last_modified: 2022-12-14 18:05:23.086656+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-058-006
  eft-text-version: 1.1.2 2020
  title: Toh_157-The_Questions_of_the_Kimnara_King_Druma-v2
bases:
  70E6:
    source_metadata: null
    order: 1
    base_file: 70E6.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
